### ISSUE TITLE
Elasticsearch 5.x bulk response

### ISSUE THREAD

**Issue by megastef** [mcollina/pino-elasticsearch#6]
Items returned in Elasticsearch 5.x might have a property "index" instead of "create" - both should be checked. 
https://github.com/mcollina/pino-elasticsearch/blob/master/pino-elasticsearch.js#L56

**Comment by megastef** [comment]
https://github.com/mcollina/pino-elasticsearch/commit/358a3d746cfbc56a6e03c7cff68fdfc40273dc79 included in PR https://github.com/mcollina/pino-elasticsearch/pull/5

**Comment by mcollina** [comment]
Fixed in #5
